// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {history} from '../models';
import {main} from '../models';
import {config} from '../models';

export function Connect(arg1:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DescribeTable(arg1:string,arg2:string):Promise<db.TableDescription>;

export function Disconnect():Promise<void>;

export function ExportDocResultJSONL():Promise<string>;

export function ExportResultCSV():Promise<string>;

export function Find(arg1:string,arg2:string,arg3:string):Promise<db.DocResult>;

export function GetHistory(arg1:number,arg2:string):Promise<Array<history.HistoryEntry>>;

export function GetLogs():Promise<Array<string>>;

export function GetStatus():Promise<main.StatusPayload>;

export function GetValue(arg1:number,arg2:string):Promise<db.KVValue>;

export function IndexInfo(arg1:string,arg2:string):Promise<Array<db.IndexInfo>>;

export function KeyType(arg1:number,arg2:string):Promise<string>;

export function ListCollections(arg1:string):Promise<Array<string>>;

export function ListConnections():Promise<Array<config.Connection>>;

export function ListMongoDatabases():Promise<Array<string>>;

export function ListRedisDatabases():Promise<Array<number>>;

export function ListSQLDatabases():Promise<Array<string>>;

export function ListSchemas():Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<db.TableRef>>;

export function RunKVCommand(arg1:number,arg2:string,arg3:boolean):Promise<main.KVCommandResult>;

export function RunQuery(arg1:string):Promise<db.QueryResult>;

export function SaveConnection(arg1:string,arg2:config.Connection,arg3:string):Promise<void>;

export function ScanKeys(arg1:number,arg2:string):Promise<Array<string>>;

export function SwitchDatabase(arg1:string):Promise<void>;

export function TTLSeconds(arg1:number,arg2:string):Promise<number>;
