// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DescribeTable(arg1, arg2) {
  return window['go']['main']['App']['DescribeTable'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportDocResultJSONL() {
  return window['go']['main']['App']['ExportDocResultJSONL']();
}

export function ExportResultCSV() {
  return window['go']['main']['App']['ExportResultCSV']();
}

export function Find(arg1, arg2, arg3) {
  return window['go']['main']['App']['Find'](arg1, arg2, arg3);
}

export function GetHistory(arg1, arg2) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetValue(arg1, arg2) {
  return window['go']['main']['App']['GetValue'](arg1, arg2);
}

export function IndexInfo(arg1, arg2) {
  return window['go']['main']['App']['IndexInfo'](arg1, arg2);
}

export function KeyType(arg1, arg2) {
  return window['go']['main']['App']['KeyType'](arg1, arg2);
}

export function ListCollections(arg1) {
  return window['go']['main']['App']['ListCollections'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListMongoDatabases() {
  return window['go']['main']['App']['ListMongoDatabases']();
}

export function ListRedisDatabases() {
  return window['go']['main']['App']['ListRedisDatabases']();
}

export function ListSQLDatabases() {
  return window['go']['main']['App']['ListSQLDatabases']();
}

export function ListSchemas() {
  return window['go']['main']['App']['ListSchemas']();
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function RunKVCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunKVCommand'](arg1, arg2, arg3);
}

export function RunQuery(arg1) {
  return window['go']['main']['App']['RunQuery'](arg1);
}

export function SaveConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2, arg3);
}

export function ScanKeys(arg1, arg2) {
  return window['go']['main']['App']['ScanKeys'](arg1, arg2);
}

export function SwitchDatabase(arg1) {
  return window['go']['main']['App']['SwitchDatabase'](arg1);
}

export function TTLSeconds(arg1, arg2) {
  return window['go']['main']['App']['TTLSeconds'](arg1, arg2);
}
